use_frameworks!
inhibit_all_warnings!
target 'YCRequest_Example' do
  pod 'YCRequest', :path => '../'
  pod 'YYModel'
  target 'YCRequest_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end
